In [1]:
# https://numpy.org/

In [2]:
import numpy as np

In [3]:
my_list = [10,20,30,40]

In [4]:
my_numpy_array = np.array(my_list)

In [5]:
my_numpy_array

array([10, 20, 30, 40])

In [6]:
my_numpy_array.max()

np.int64(40)

In [7]:
# array arithmetic

In [8]:
my_other_array = np.array([10,20,30,40,50])

In [9]:
my_other_array.min()

np.int64(10)

In [10]:
my_other_array.sum()

np.int64(150)

In [11]:
int(my_numpy_array.max())

40

In [12]:
# arange & indexing

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np_array = np.arange(0,10)

In [16]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np_array[1:4:]

array([1, 2, 3])

In [18]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
np_array[2:6:2]

array([2, 4])

In [20]:
# random

In [21]:
np.random.rand(4,4)

array([[0.58580609, 0.1447218 , 0.1217562 , 0.42585269],
       [0.24178112, 0.906887  , 0.8571055 , 0.1335307 ],
       [0.80265541, 0.56070498, 0.51627235, 0.44747945],
       [0.62837447, 0.73465315, 0.35642636, 0.5588286 ]])

In [22]:
np.random.randint(1,300,5)

array([ 57,  25,  60,  59, 234], dtype=int32)