In [1]:
# https://numpy.org/

In [2]:
import numpy as np

In [3]:
my_matrix = [[5,10],[15,20]]

In [4]:
my_matrix[0]

[5, 10]

In [5]:
my_matrix[0][1]

10

In [6]:
# row * column

In [7]:
numpy_matrix = np.array([[5,10],[15,20]])

In [8]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [9]:
numpy_matrix.sum()

np.int64(50)

In [10]:
int(numpy_matrix.sum())

50

In [11]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.random.random((3,2))

array([[0.53079925, 0.84614212],
       [0.37937365, 0.35611998],
       [0.62929345, 0.25066622]])

In [13]:
# matrix arithmetic

In [14]:
first_array = np.array([[10,20],[30,40]])

In [15]:
second_array = np.array([[5,15],[25,35]])

In [16]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [17]:
second_array.shape

(2, 2)

In [18]:
# matrix multiplication (dot product)

In [19]:
first_matrix = np.array([[10,20,30]])

In [20]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [21]:
first_matrix.shape

(1, 3)

In [22]:
second_matrix.shape

(3, 2)

In [23]:
result_matrix = first_matrix.dot(second_matrix)

In [24]:
result_matrix

array([[120, 180]])

In [25]:
result_matrix.shape

(1, 2)