In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([49, 49, 95, 31, 96, 74, 52,  1, 10, 47, 92, 79, 21, 72, 83, 62, 42,
       47, 35, 99], dtype=int32)

In [4]:
new_array[new_array > 25]

array([49, 49, 95, 31, 96, 74, 52, 47, 92, 79, 72, 83, 62, 42, 47, 35, 99],
      dtype=int32)

In [5]:
# transpose & reshape

In [7]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [8]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [9]:
matrix_array.shape

(3, 2)

In [10]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [11]:
matrix_array.reshape(2,3)

array([[10, 20, 20],
       [30, 30, 40]])