In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([28, 35, 10, 31, 79, 81, 39, 93, 57, 24, 21, 57, 37, 65, 23, 60, 67,
       34, 92, 18], dtype=int32)

In [4]:
new_array[new_array > 25]

array([28, 35, 31, 79, 81, 39, 93, 57, 57, 37, 65, 60, 67, 34, 92],
      dtype=int32)

In [5]:
# transpose & reshape

In [6]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [7]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [8]:
matrix_array.shape

(3, 2)

In [9]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [10]:
matrix_array.reshape(2,3)

array([[10, 20, 20],
       [30, 30, 40]])