In [1]:
# https://github.com/shankarpandala/lazypredict

In [2]:
from lazypredict.Supervised import LazyRegressor
from sklearn import datasets
from sklearn.utils import shuffle
import numpy as np

In [3]:
diabetes  = datasets.load_diabetes()
type(diabetes)

sklearn.utils._bunch.Bunch

In [4]:
diabetes["DESCR"]

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of thes

In [5]:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [6]:
X, y = shuffle(diabetes.data, diabetes.target, random_state=13)

In [7]:
X = X.astype(np.float32)

In [8]:
offset = int(X.shape[0] * 0.9)

X_train, y_train = X[:offset], y[:offset]
X_test, y_test = X[offset:], y[offset:]

In [9]:
X_train

array([[-0.00551456, -0.04464164,  0.05630714, ...,  0.03799897,
         0.05078203,  0.0569118 ],
       [-0.02004471, -0.04464164, -0.08488624, ..., -0.05167075,
        -0.08237869, -0.04664087],
       [-0.06726771, -0.04464164, -0.05901875, ..., -0.03949338,
         0.00200444,  0.02377494],
       ...,
       [-0.02367725, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.08913335, -0.05078298],
       [ 0.07440129, -0.04464164,  0.114509  , ..., -0.00259226,
        -0.00061174, -0.0052198 ],
       [ 0.01991321,  0.05068012,  0.01427248, ...,  0.03430886,
         0.04666178,  0.09004866]], shape=(397, 10), dtype=float32)

In [10]:
X[0]

array([-0.00551456, -0.04464164,  0.05630714, -0.03665608, -0.04835136,
       -0.04296262, -0.07285395,  0.03799897,  0.05078203,  0.0569118 ],
      dtype=float32)

In [11]:
y[0]

np.float64(272.0)

In [12]:
reg = LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None) # verbose : controls the amount of output messages (0 = silent mode)

In [13]:
models, predictions = reg.fit(X_train, X_test, y_train, y_test)

  0%|          | 0/42 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000042 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 640
[LightGBM] [Info] Number of data points in the train set: 397, number of used features: 10
[LightGBM] [Info] Start training from score 151.722922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: 

In [14]:
print(models)

                               Adjusted R-Squared  R-Squared   RMSE  \
Model                                                                 
ExtraTreesRegressor                          0.38       0.52  54.22   
OrthogonalMatchingPursuitCV                  0.37       0.52  54.39   
Lasso                                        0.37       0.52  54.46   
LassoLars                                    0.37       0.52  54.46   
LarsCV                                       0.37       0.51  54.54   
LassoCV                                      0.37       0.51  54.59   
PassiveAggressiveRegressor                   0.37       0.51  54.74   
LassoLarsIC                                  0.36       0.51  54.83   
SGDRegressor                                 0.36       0.51  54.85   
Ridge                                        0.36       0.51  54.91   
RidgeCV                                      0.36       0.51  54.91   
BayesianRidge                                0.36       0.51  54.94   
LassoL